[package]
name        = "prolly-rust"
version     = "0.1.0"
edition     = "2024"

[lib]
crate-type = ["cdylib"] # wasm‑bindgen JS glue

[features]
ipld  = []
json  = []
sql   = ["dep:rusqlite"]


[dependencies]
async-trait = "0.1"
wasm-bindgen = "0.2"
js-sys      = "0.3"
blake3       = "1.5"
getrandom    = { version = "0.2", features = ["js"] }
bincode      = "1.3"
serde       = { version = "1", features = ["derive"] }
serde_json  = { version = "1" }
thiserror = "1.0"
tokio = { version = "1", features = ["sync", "macros"] }
rusqlite     = { version = "0.31", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
