[package]
name = "prolly-rust"
version = "0.1.0"
edition = "2024" 

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4" 
gloo-console = "0.3"
async-recursion = "1.0" # Check for latest 1.x
futures = "0.3.31" 
wasm-bindgen = "0.2.100"        
wasm-bindgen-futures = "0.4.50" 
js-sys = "0.3.77"               
tokio = { version = "1.45.0", features = ["sync", "macros", "rt"] } # Match log, add "rt" for safety
fastcdc = "3.2.1"               # Match log if possible, or latest 3.x
serde = { version = "1.0.219", features = ["derive"] } # Match log
serde_json = { version = "1.0.140", features = ["preserve_order"] } # Match log
serde-wasm-bindgen = "0.6.5"
bincode = "1.3.3"  
crc32fast = "1.4.2"  
chrono = { version = "0.4", features = ["serde"] }   
byteorder = "1.4"        
blake3 = "1.8.2"                
thiserror = "1.0.69"            
async-trait = "0.1.88"          
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"   

[features]
default = ["console_error_panic_hook"]