[package]
name        = "prolly-rust"
version     = "0.1.0"
edition     = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
wasm-bindgen = "0.2.92" # Or latest
wasm-bindgen-futures = "0.4.42" # Or latest
js-sys = "0.3.69" # Or latest
tokio = { version = "1", features = ["sync", "macros"] } # Ensure rt-multi-thread for wasm-bindgen-test with tokio::spawn
fastcdc = "3.0" # Or latest compatible version
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
blake3 = "1.5"
thiserror = "1.0"
async-trait = "0.1"
console_error_panic_hook = { version = "0.1.7", optional = true } # Good for debugging wasm panics
# wasm-logger = "0.2.0" # Optional, for logging in wasm tests

[dev-dependencies]
wasm-bindgen-test = "0.3.42" # Or latest

[features]
default = ["console_error_panic_hook"]